### PR TITLE
Pin boto to version 2.34.0; fix URL for eucaconsole GitHub repo; add gitignore file

### PR DESCRIPTION
**Pull request by kamalgill**
Avoid using Boto 2.35 or 2.36 due to https://github.com/boto/boto/issues/2885

Possible fix for https://eucalyptus.atlassian.net/browse/GUI-1609

### CODE REVIEW

**Comment by gholms** [comment]
I am already holding EPEL's python-boto package back until that bug is fixed.  (See https://bugzilla.redhat.com/show_bug.cgi?id=1180861.)  What are you trying to solve with this change?  Is a newer version creeping in from somewhere else?

As far as code review goes, rpm spec files use `=` for version equality, not `==`.  This commit also adds a spurious .gitignore entry that is not necessary in this repository.

**Comment by gholms** [comment]
Oops, I missed one additional bit:  BuildRequires entries are used at build time for things like byte-compiling and running unit tests.  If your goal is to change what winds up on one's system when installing the package then take a look at the regular Requires entries instead.

**Comment by kamalgill** [comment]
@gholms: It's fairly clear in the description what this PR hoped to fix (for GUI-1609).  However, since the boto version wasn't the culprit there, and since you appear to control what version ends up in EPEL (which I wasn't aware of), we can close this PR w/o merging.  With respect to the BuildRequires bit, that part was already there, I only attempted to pin the version by using '==' instead of '>='.  Finally, I received a blatant warning that this repo doesn't include a .gitignore file when I opened it in my IDE, so I would hesitate to call that entry "spurious"

**Comment by gholms** [comment]
Given that the bug the description linked to mentioned no systems with python-boto > 2.34.0, it was not clear what this pull request was intended to fix.  I apologize if asking for more information offended you.

My comments about the dependency change seem to have been unclear, so I will elaborate a little more about them for future reference:

1.  Spec files use single `=` characters for equality, not double `==` characters.
2.  You changed the` BuildRequires` entry for python-boto, which would have no effect on end users' systems.  Regular `Requires` entries are the things to change for that.

On that note, I just discovered that this package somehow managed to slip by with no python-boto dependency at all, so I will file a bug for that shortly.  I can see now why my reply was confusing.  Good catch!

**Pull request closed without merging**
